import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
	{
		path: '',
		redirectTo: 'home',
		pathMatch: 'full'
	},
	{
		path: 'home',
		loadChildren: () => import('./pages/home/home.module').then(m => m.HomePageModule)
	},
	{ path: 'site-menu', loadChildren: './pages/capacitor/site-menu/site-menu.module#SiteMenuPageModule' },
	{ path: 'anchor-link', loadChildren: './pages/capacitor/anchor-link/anchor-link.module#AnchorLinkPageModule' },
	{ path: 'app-burger', loadChildren: './pages/capacitor/app-burger/app-burger.module#AppBurgerPageModule' },
	{ path: 'app-icon', loadChildren: './pages/capacitor/app-icon/app-icon.module#AppIconPageModule' },
	{ path: 'app-marked', loadChildren: './pages/capacitor/app-marked/app-marked.module#AppMarkedPageModule' },
	{ path: 'avc-code-type', loadChildren: './pages/capacitor/avc-code-type/avc-code-type.module#AvcCodeTypePageModule' },
	{ path: 'blog-page', loadChildren: './pages/capacitor/blog-page/blog-page.module#BlogPagePageModule' },
	{ path: 'capacitor-site', loadChildren: './pages/capacitor/capacitor-site/capacitor-site.module#CapacitorSitePageModule' },
	{ path: 'contributor-list', loadChildren: './pages/capacitor/contributor-list/contributor-list.module#ContributorListPageModule' },
	{ path: 'demos-page', loadChildren: './pages/capacitor/demos-page/demos-page.module#DemosPagePageModule' },
	{ path: 'doc-snippet', loadChildren: './pages/capacitor/doc-snippet/doc-snippet.module#DocSnippetPageModule' },
	{ path: 'document-component', loadChildren: './pages/capacitor/document-component/document-component.module#DocumentComponentPageModule' },
	{ path: 'in-page-navigation', loadChildren: './pages/capacitor/in-page-navigation/in-page-navigation.module#InPageNavigationPageModule' },
	{ path: 'landing-page', loadChildren: './pages/capacitor/landing-page/landing-page.module#LandingPagePageModule' },
	{ path: 'lower-content-nav', loadChildren: './pages/capacitor/lower-content-nav/lower-content-nav.module#LowerContentNavPageModule' },
	{ path: 'newsletter-signup', loadChildren: './pages/capacitor/newsletter-signup/newsletter-signup.module#NewsletterSignupPageModule' },
	{ path: 'plugin-api', loadChildren: './pages/capacitor/plugin-api/plugin-api.module#PluginApiPageModule' },
	{ path: 'plugin-platforms', loadChildren: './pages/capacitor/plugin-platforms/plugin-platforms.module#PluginPlatformsPageModule' },
	{ path: 'site-bar', loadChildren: './pages/capacitor/site-bar/site-bar.module#SiteBarPageModule' },
	{ path: 'site-header', loadChildren: './pages/capacitor/site-header/site-header.module#SiteHeaderPageModule' },
	{ path: 'action-sheet', loadChildren: './pages/source/action-sheet/action-sheet.module#ActionSheetPageModule' },
	{ path: 'alert', loadChildren: './pages/source/alert/alert.module#AlertPageModule' },
	{ path: 'anchor', loadChildren: './pages/source/anchor/anchor.module#AnchorPageModule' },
	{ path: 'app', loadChildren: './pages/source/app/app.module#AppPageModule' },
	{ path: 'avatar', loadChildren: './pages/source/avatar/avatar.module#AvatarPageModule' },
	{ path: 'back-button', loadChildren: './pages/source/back-button/back-button.module#BackButtonPageModule' },
	{ path: 'badge', loadChildren: './pages/source/badge/badge.module#BadgePageModule' },
	{ path: 'button', loadChildren: './pages/source/button/button.module#ButtonPageModule' },
	{ path: 'buttons', loadChildren: './pages/source/buttons/buttons.module#ButtonsPageModule' },
	{ path: 'card-header', loadChildren: './pages/source/card-header/card-header.module#CardHeaderPageModule' },
	{ path: 'card', loadChildren: './pages/source/card/card.module#CardPageModule' },
	{ path: 'checkbox', loadChildren: './pages/source/checkbox/checkbox.module#CheckboxPageModule' },
	{ path: 'chip', loadChildren: './pages/source/chip/chip.module#ChipPageModule' },
	{ path: 'content', loadChildren: './pages/source/content/content.module#ContentPageModule' },
	{ path: 'datetime', loadChildren: './pages/source/datetime/datetime.module#DatetimePageModule' },
	{ path: 'fab-button', loadChildren: './pages/source/fab-button/fab-button.module#FabButtonPageModule' },
	{ path: 'fab', loadChildren: './pages/source/fab/fab.module#FabPageModule' },
	{ path: 'footer', loadChildren: './pages/source/footer/footer.module#FooterPageModule' },
	{ path: 'grid', loadChildren: './pages/source/grid/grid.module#GridPageModule' },
	{ path: 'header', loadChildren: './pages/source/header/header.module#HeaderPageModule' },
	{ path: 'icon', loadChildren: './pages/source/icon/icon.module#IconPageModule' },
	{ path: 'img', loadChildren: './pages/source/img/img.module#ImgPageModule' },
	{ path: 'infinite-scroll', loadChildren: './pages/source/infinite-scroll/infinite-scroll.module#InfiniteScrollPageModule' },
	{ path: 'input', loadChildren: './pages/source/input/input.module#InputPageModule' },
	{ path: 'item-divider', loadChildren: './pages/source/item-divider/item-divider.module#ItemDividerPageModule' },
	{ path: 'item-sliding', loadChildren: './pages/source/item-sliding/item-sliding.module#ItemSlidingPageModule' },
	{ path: 'item', loadChildren: './pages/source/item/item.module#ItemPageModule' },
	{ path: 'label', loadChildren: './pages/source/label/label.module#LabelPageModule' },
	{ path: 'list', loadChildren: './pages/source/list/list.module#ListPageModule' },
	{ path: 'loading', loadChildren: './pages/source/loading/loading.module#LoadingPageModule' },
	{ path: 'menu-button', loadChildren: './pages/source/menu-button/menu-button.module#MenuButtonPageModule' },
	{ path: 'menu-toggle', loadChildren: './pages/source/menu-toggle/menu-toggle.module#MenuTogglePageModule' },
	{ path: 'menu', loadChildren: './pages/source/menu/menu.module#MenuPageModule' },
	{ path: 'modal', loadChildren: './pages/source/modal/modal.module#ModalPageModule' },
	{ path: 'nav-link', loadChildren: './pages/source/nav-link/nav-link.module#NavLinkPageModule' },
	{ path: 'nav-pop', loadChildren: './pages/source/nav-pop/nav-pop.module#NavPopPageModule' },
	{ path: 'nav-push', loadChildren: './pages/source/nav-push/nav-push.module#NavPushPageModule' },
	{ path: 'nav-set-root', loadChildren: './pages/source/nav-set-root/nav-set-root.module#NavSetRootPageModule' },
	{ path: 'nav', loadChildren: './pages/source/nav/nav.module#NavPageModule' },
	{ path: 'note', loadChildren: './pages/source/note/note.module#NotePageModule' },
	{ path: 'picker-column', loadChildren: './pages/source/picker-column/picker-column.module#PickerColumnPageModule' },
	{ path: 'picker', loadChildren: './pages/source/picker/picker.module#PickerPageModule' },
	{ path: 'popover', loadChildren: './pages/source/popover/popover.module#PopoverPageModule' },
	{ path: 'progress-bar', loadChildren: './pages/source/progress-bar/progress-bar.module#ProgressBarPageModule' },
	{ path: 'radio-group', loadChildren: './pages/source/radio-group/radio-group.module#RadioGroupPageModule' },
	{ path: 'radio', loadChildren: './pages/source/radio/radio.module#RadioPageModule' },
	{ path: 'range', loadChildren: './pages/source/range/range.module#RangePageModule' },
	{ path: 'refresher', loadChildren: './pages/source/refresher/refresher.module#RefresherPageModule' },
	{ path: 'reorder-group', loadChildren: './pages/source/reorder-group/reorder-group.module#ReorderGroupPageModule' },
	{ path: 'ripple-effect', loadChildren: './pages/source/ripple-effect/ripple-effect.module#RippleEffectPageModule' },
	{ path: 'router-link', loadChildren: './pages/source/router-link/router-link.module#RouterLinkPageModule' },
	{ path: 'router-outlet', loadChildren: './pages/source/router-outlet/router-outlet.module#RouterOutletPageModule' },
	{ path: 'router', loadChildren: './pages/source/router/router.module#RouterPageModule' },
	{ path: 'searchbar', loadChildren: './pages/source/searchbar/searchbar.module#SearchbarPageModule' },
	{ path: 'segment', loadChildren: './pages/source/segment/segment.module#SegmentPageModule' },
	{ path: 'select', loadChildren: './pages/source/select/select.module#SelectPageModule' },
	{ path: 'skeleton-text', loadChildren: './pages/source/skeleton-text/skeleton-text.module#SkeletonTextPageModule' },
	{ path: 'slides', loadChildren: './pages/source/slides/slides.module#SlidesPageModule' },
	{ path: 'spinner', loadChildren: './pages/source/spinner/spinner.module#SpinnerPageModule' },
	{ path: 'split-pane', loadChildren: './pages/source/split-pane/split-pane.module#SplitPanePageModule' },
	{ path: 'tab-bar', loadChildren: './pages/source/tab-bar/tab-bar.module#TabBarPageModule' },
	{ path: 'tabs', loadChildren: './pages/source/tabs/tabs.module#TabsPageModule' },
	{ path: 'text', loadChildren: './pages/source/text/text.module#TextPageModule' },
	{ path: 'textarea', loadChildren: './pages/source/textarea/textarea.module#TextareaPageModule' },
	{ path: 'thumbnail', loadChildren: './pages/source/thumbnail/thumbnail.module#ThumbnailPageModule' },
	{ path: 'title', loadChildren: './pages/source/title/title.module#TitlePageModule' },
	{ path: 'toast', loadChildren: './pages/source/toast/toast.module#ToastPageModule' },
	{ path: 'toggle', loadChildren: './pages/source/toggle/toggle.module#TogglePageModule' },
	{ path: 'toolbar', loadChildren: './pages/source/toolbar/toolbar.module#ToolbarPageModule' },
	{ path: 'virtual-scroll', loadChildren: './pages/source/virtual-scroll/virtual-scroll.module#VirtualScrollPageModule' },
	{ path: 'action-sheets', loadChildren: './pages/preview/action-sheets/action-sheets.module#ActionSheetsPageModule' },
	{ path: 'alerts', loadChildren: './pages/preview/alerts/alerts.module#AlertsPageModule' },
	{ path: 'badges', loadChildren: './pages/preview/badges/badges.module#BadgesPageModule' },
	{ path: 'buttons', loadChildren: './pages/preview/buttons/buttons.module#ButtonsPageModule' },
	{ path: 'cards', loadChildren: './pages/preview/cards/cards.module#CardsPageModule' },
	{ path: 'checkboxes', loadChildren: './pages/preview/checkboxes/checkboxes.module#CheckboxesPageModule' },
	{ path: 'datetime', loadChildren: './pages/preview/datetime/datetime.module#DatetimePageModule' },
	{ path: 'fabs', loadChildren: './pages/preview/fabs/fabs.module#FabsPageModule' },
	{ path: 'gestures', loadChildren: './pages/preview/gestures/gestures.module#GesturesPageModule' },
	{ path: 'grid', loadChildren: './pages/preview/grid/grid.module#GridPageModule' },
	{ path: 'icons', loadChildren: './pages/preview/icons/icons.module#IconsPageModule' },
	{ path: 'inputs', loadChildren: './pages/preview/inputs/inputs.module#InputsPageModule' },
	{ path: 'lists', loadChildren: './pages/preview/lists/lists.module#ListsPageModule' },
	{ path: 'loading', loadChildren: './pages/preview/loading/loading.module#LoadingPageModule' },
	{ path: 'menus', loadChildren: './pages/preview/menus/menus.module#MenusPageModule' },
	{ path: 'modals', loadChildren: './pages/preview/modals/modals.module#ModalsPageModule' },
	{ path: 'navigation', loadChildren: './pages/preview/navigation/navigation.module#NavigationPageModule' },
	{ path: 'popovers', loadChildren: './pages/preview/popovers/popovers.module#PopoversPageModule' },
	{ path: 'radios', loadChildren: './pages/preview/radios/radios.module#RadiosPageModule' },
	{ path: 'ranges', loadChildren: './pages/preview/ranges/ranges.module#RangesPageModule' },
	{ path: 'searchbars', loadChildren: './pages/preview/searchbars/searchbars.module#SearchbarsPageModule' },
	{ path: 'segments', loadChildren: './pages/preview/segments/segments.module#SegmentsPageModule' },
	{ path: 'selects', loadChildren: './pages/preview/selects/selects.module#SelectsPageModule' },
	{ path: 'slides', loadChildren: './pages/preview/slides/slides.module#SlidesPageModule' },
	{ path: 'tabs', loadChildren: './pages/preview/tabs/tabs.module#TabsPageModule' },
	{ path: 'toast', loadChildren: './pages/preview/toast/toast.module#ToastPageModule' },
	{ path: 'toggles', loadChildren: './pages/preview/toggles/toggles.module#TogglesPageModule' },
	{ path: 'toolbar', loadChildren: './pages/preview/toolbar/toolbar.module#ToolbarPageModule' },
	{ path: 'action-sheet', loadChildren: './pages/preview-component/action-sheet/action-sheet.module#ActionSheetPageModule' },
	{ path: 'alert', loadChildren: './pages/preview-component/alert/alert.module#AlertPageModule' },
	{ path: 'badge', loadChildren: './pages/preview-component/badge/badge.module#BadgePageModule' },
	{ path: 'button', loadChildren: './pages/preview-component/button/button.module#ButtonPageModule' },
	{ path: 'card', loadChildren: './pages/preview-component/card/card.module#CardPageModule' },
	{ path: 'checkbox', loadChildren: './pages/preview-component/checkbox/checkbox.module#CheckboxPageModule' },
	{ path: 'component-preview', loadChildren: './pages/preview-component/component-preview/component-preview.module#ComponentPreviewPageModule' },
	{ path: 'datetime', loadChildren: './pages/preview-component/datetime/datetime.module#DatetimePageModule' },
	{ path: 'fab', loadChildren: './pages/preview-component/fab/fab.module#FabPageModule' },
	{ path: 'grid', loadChildren: './pages/preview-component/grid/grid.module#GridPageModule' },
	{ path: 'infinite-scroll', loadChildren: './pages/preview-component/infinite-scroll/infinite-scroll.module#InfiniteScrollPageModule' },
	{ path: 'input', loadChildren: './pages/preview-component/input/input.module#InputPageModule' },
	{ path: 'list', loadChildren: './pages/preview-component/list/list.module#ListPageModule' },
	{ path: 'loading', loadChildren: './pages/preview-component/loading/loading.module#LoadingPageModule' },
	{ path: 'menu', loadChildren: './pages/preview-component/menu/menu.module#MenuPageModule' },
	{ path: 'modal', loadChildren: './pages/preview-component/modal/modal.module#ModalPageModule' },
	{ path: 'nav', loadChildren: './pages/preview-component/nav/nav.module#NavPageModule' },
	{ path: 'page-index', loadChildren: './pages/preview-component/page-index/page-index.module#PageIndexPageModule' },
	{ path: 'popover', loadChildren: './pages/preview-component/popover/popover.module#PopoverPageModule' },
	{ path: 'range', loadChildren: './pages/preview-component/range/range.module#RangePageModule' },
	{ path: 'refresher', loadChildren: './pages/preview-component/refresher/refresher.module#RefresherPageModule' },
	{ path: 'searchbar', loadChildren: './pages/preview-component/searchbar/searchbar.module#SearchbarPageModule' },
	{ path: 'select', loadChildren: './pages/preview-component/select/select.module#SelectPageModule' },
	{ path: 'slides', loadChildren: './pages/preview-component/slides/slides.module#SlidesPageModule' },
	{ path: 'spinner', loadChildren: './pages/preview-component/spinner/spinner.module#SpinnerPageModule' },
	{ path: 'tabs', loadChildren: './pages/preview-component/tabs/tabs.module#TabsPageModule' },
	{ path: 'toast', loadChildren: './pages/preview-component/toast/toast.module#ToastPageModule' },
	{ path: 'virtual-scroll', loadChildren: './pages/preview-component/virtual-scroll/virtual-scroll.module#VirtualScrollPageModule' }
];

@NgModule({
	imports: [
		RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
	],
	exports: [RouterModule]
})
export class AppRoutingModule { }
