import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
	{ path: '', redirectTo: 'home', pathMatch: 'full' },
	{ path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomePageModule) },

	{ path: 'action-sheet', loadChildren: () => import('./pages/action-sheet/action-sheet.module').then(m => m.ActionSheetPageModule) },
	{ path: 'alert', loadChildren: () => import('./pages/alert/alert.module').then(m => m.AlertPageModule) },
	{ path: 'anchor-link/capacitor', loadChildren: () => import('./pages/anchor-link/capacitor/anchor-link.module').then(m => m.AnchorLinkPageModule) },
	{ path: 'anchor/source', loadChildren: () => import('./pages/anchor/source/anchor.module').then(m => m.AnchorPageModule) },
	{ path: 'app-burger/capacitor', loadChildren: () => import('./pages/app-burger/capacitor/app-burger.module').then(m => m.AppBurgerPageModule) },
	{ path: 'app-icon/capacitor', loadChildren: () => import('./pages/app-icon/capacitor/app-icon.module').then(m => m.AppIconPageModule) },
	{ path: 'app-marked/capacitor', loadChildren: () => import('./pages/app-marked/capacitor/app-marked.module').then(m => m.AppMarkedPageModule) },
	{ path: 'app/source', loadChildren: () => import('./pages/app/source/app.module').then(m => m.AppPageModule) },
	{ path: 'avatar', loadChildren: () => import('./pages/avatar/avatar.module').then(m => m.AvatarPageModule) },
	{ path: 'avc-code-type/capacitor', loadChildren: () => import('./pages/avc-code-type/capacitor/avc-code-type.module').then(m => m.AvcCodeTypePageModule) },
	{ path: 'back-button', loadChildren: () => import('./pages/back-button/back-button.module').then(m => m.BackButtonPageModule) },
	{ path: 'backdrop', loadChildren: () => import('./pages/backdrop/backdrop.module').then(m => m.BackdropPageModule) },
	{ path: 'badge', loadChildren: () => import('./pages/badge/badge.module').then(m => m.BadgePageModule) },
	{ path: 'blog-page/capacitor', loadChildren: () => import('./pages/blog-page/capacitor/blog-page.module').then(m => m.BlogPagePageModule) },
	{ path: 'button', loadChildren: () => import('./pages/button/button.module').then(m => m.ButtonPageModule) },
	{ path: 'capacitor-site/capacitor', loadChildren: () => import('./pages/capacitor-site/capacitor/capacitor-site.module').then(m => m.CapacitorSitePageModule) },
	{ path: 'card-header/source', loadChildren: () => import('./pages/card-header/source/card-header.module').then(m => m.CardHeaderPageModule) },
	{ path: 'card', loadChildren: () => import('./pages/card/card.module').then(m => m.CardPageModule) },
	{ path: 'checkbox', loadChildren: () => import('./pages/checkbox/checkbox.module').then(m => m.CheckboxPageModule) },
	{ path: 'chip', loadChildren: () => import('./pages/chip/chip.module').then(m => m.ChipPageModule) },
	{ path: 'component-preview/preview-component', loadChildren: () => import('./pages/component-preview/preview-component/component-preview.module').then(m => m.ComponentPreviewPageModule) },
	{ path: 'content', loadChildren: () => import('./pages/content/content.module').then(m => m.ContentPageModule) },
	{ path: 'contributor-list/capacitor', loadChildren: () => import('./pages/contributor-list/capacitor/contributor-list.module').then(m => m.ContributorListPageModule) },
	{ path: 'datetime', loadChildren: () => import('./pages/datetime/datetime.module').then(m => m.DatetimePageModule) },
	{ path: 'demos-page/capacitor', loadChildren: () => import('./pages/demos-page/capacitor/demos-page.module').then(m => m.DemosPagePageModule) },
	{ path: 'doc-snippet/capacitor', loadChildren: () => import('./pages/doc-snippet/capacitor/doc-snippet.module').then(m => m.DocSnippetPageModule) },
	{ path: 'document-component/capacitor', loadChildren: () => import('./pages/document-component/capacitor/document-component.module').then(m => m.DocumentComponentPageModule) },
	{ path: 'fab-button/source', loadChildren: () => import('./pages/fab-button/source/fab-button.module').then(m => m.FabButtonPageModule) },
	{ path: 'fab', loadChildren: () => import('./pages/fab/fab.module').then(m => m.FabPageModule) },
	{ path: 'footer/source', loadChildren: () => import('./pages/footer/source/footer.module').then(m => m.FooterPageModule) },
	{ path: 'gestures/preview', loadChildren: () => import('./pages/gestures/preview/gestures.module').then(m => m.GesturesPageModule) },
	{ path: 'grid', loadChildren: () => import('./pages/grid/grid.module').then(m => m.GridPageModule) },
	{ path: 'header/source', loadChildren: () => import('./pages/header/source/header.module').then(m => m.HeaderPageModule) },
	{ path: 'icon', loadChildren: () => import('./pages/icon/icon.module').then(m => m.IconPageModule) },
	{ path: 'img/source', loadChildren: () => import('./pages/img/source/img.module').then(m => m.ImgPageModule) },
	{ path: 'in-page-navigation/capacitor', loadChildren: () => import('./pages/in-page-navigation/capacitor/in-page-navigation.module').then(m => m.InPageNavigationPageModule) },
	{ path: 'infinite-scroll', loadChildren: () => import('./pages/infinite-scroll/infinite-scroll.module').then(m => m.InfiniteScrollPageModule) },
	{ path: 'input', loadChildren: () => import('./pages/input/input.module').then(m => m.InputPageModule) },
	{ path: 'item-divider/source', loadChildren: () => import('./pages/item-divider/source/item-divider.module').then(m => m.ItemDividerPageModule) },
	{ path: 'item-sliding/source', loadChildren: () => import('./pages/item-sliding/source/item-sliding.module').then(m => m.ItemSlidingPageModule) },
	{ path: 'item', loadChildren: () => import('./pages/item/item.module').then(m => m.ItemPageModule) },
	{ path: 'item/source', loadChildren: () => import('./pages/item/source/item.module').then(m => m.ItemPageModule) },
	{ path: 'label/source', loadChildren: () => import('./pages/label/source/label.module').then(m => m.LabelPageModule) },
	{ path: 'landing-page/capacitor', loadChildren: () => import('./pages/landing-page/capacitor/landing-page.module').then(m => m.LandingPagePageModule) },
	{ path: 'list', loadChildren: () => import('./pages/list/list.module').then(m => m.ListPageModule) },
	{ path: 'loading', loadChildren: () => import('./pages/loading/loading.module').then(m => m.LoadingPageModule) },
	{ path: 'lower-content-nav/capacitor', loadChildren: () => import('./pages/lower-content-nav/capacitor/lower-content-nav.module').then(m => m.LowerContentNavPageModule) },
	{ path: 'menu-button/source', loadChildren: () => import('./pages/menu-button/source/menu-button.module').then(m => m.MenuButtonPageModule) },
	{ path: 'menu-toggle/source', loadChildren: () => import('./pages/menu-toggle/source/menu-toggle.module').then(m => m.MenuTogglePageModule) },
	{ path: 'menu', loadChildren: () => import('./pages/menu/menu.module').then(m => m.MenuPageModule) },
	{ path: 'modal', loadChildren: () => import('./pages/modal/modal.module').then(m => m.ModalPageModule) },
	{ path: 'nav-link/source', loadChildren: () => import('./pages/nav-link/source/nav-link.module').then(m => m.NavLinkPageModule) },
	{ path: 'nav-pop/source', loadChildren: () => import('./pages/nav-pop/source/nav-pop.module').then(m => m.NavPopPageModule) },
	{ path: 'nav-push/source', loadChildren: () => import('./pages/nav-push/source/nav-push.module').then(m => m.NavPushPageModule) },
	{ path: 'nav-set-root/source', loadChildren: () => import('./pages/nav-set-root/source/nav-set-root.module').then(m => m.NavSetRootPageModule) },
	{ path: 'nav', loadChildren: () => import('./pages/nav/nav.module').then(m => m.NavPageModule) },
	{ path: 'navigation/preview', loadChildren: () => import('./pages/navigation/preview/navigation.module').then(m => m.NavigationPageModule) },
	{ path: 'newsletter-signup/capacitor', loadChildren: () => import('./pages/newsletter-signup/capacitor/newsletter-signup.module').then(m => m.NewsletterSignupPageModule) },
	{ path: 'note', loadChildren: () => import('./pages/note/note.module').then(m => m.NotePageModule) },
	{ path: 'note/source', loadChildren: () => import('./pages/note/source/note.module').then(m => m.NotePageModule) },
	{ path: 'page-index/preview-component', loadChildren: () => import('./pages/page-index/preview-component/page-index.module').then(m => m.PageIndexPageModule) },
	{ path: 'picker', loadChildren: () => import('./pages/picker/picker.module').then(m => m.PickerPageModule) },
	{ path: 'picker/source', loadChildren: () => import('./pages/picker/source/picker.module').then(m => m.PickerPageModule) },
	{ path: 'plugin-api/capacitor', loadChildren: () => import('./pages/plugin-api/capacitor/plugin-api.module').then(m => m.PluginApiPageModule) },
	{ path: 'plugin-platforms/capacitor', loadChildren: () => import('./pages/plugin-platforms/capacitor/plugin-platforms.module').then(m => m.PluginPlatformsPageModule) },
	{ path: 'popover', loadChildren: () => import('./pages/popover/popover.module').then(m => m.PopoverPageModule) },
	{ path: 'popover/preview-component', loadChildren: () => import('./pages/popover/preview-component/popover.module').then(m => m.PopoverPageModule) },
	{ path: 'popover/preview/basicpage', loadChildren: () => import('./pages/popover/preview/content/popover-content.module').then(m => m.PopoverContentPageModule) },
	{ path: 'popover/preview', loadChildren: () => import('./pages/popover/preview/popovers.module').then(m => m.PopoversPageModule) },
	{ path: 'popover/source', loadChildren: () => import('./pages/popover/source/popover.module').then(m => m.PopoverPageModule) },
	{ path: 'progress-bar', loadChildren: () => import('./pages/progress-bar/progress-bar.module').then(m => m.ProgressBarPageModule) },
	{ path: 'progress-bar/source', loadChildren: () => import('./pages/progress-bar/source/progress-bar.module').then(m => m.ProgressBarPageModule) },
	{ path: 'radio-group/source', loadChildren: () => import('./pages/radio-group/source/radio-group.module').then(m => m.RadioGroupPageModule) },
	{ path: 'radio', loadChildren: () => import('./pages/radio/radio.module').then(m => m.RadioPageModule) },
	{ path: 'radio/source', loadChildren: () => import('./pages/radio/source/radio.module').then(m => m.RadioPageModule) },
	{ path: 'radios/preview', loadChildren: () => import('./pages/radios/preview/radios.module').then(m => m.RadiosPageModule) },
	{ path: 'range/preview-component', loadChildren: () => import('./pages/range/preview-component/range.module').then(m => m.RangePageModule) },
	{ path: 'range/preview', loadChildren: () => import('./pages/range/preview/ranges.module').then(m => m.RangesPageModule) },
	{ path: 'range', loadChildren: () => import('./pages/range/range.module').then(m => m.RangePageModule) },
	{ path: 'range/source', loadChildren: () => import('./pages/range/source/range.module').then(m => m.RangePageModule) },
	{ path: 'refresher/preview-component', loadChildren: () => import('./pages/refresher/preview-component/refresher.module').then(m => m.RefresherPageModule) },
	{ path: 'refresher', loadChildren: () => import('./pages/refresher/refresher.module').then(m => m.RefresherPageModule) },
	{ path: 'refresher/source', loadChildren: () => import('./pages/refresher/source/refresher.module').then(m => m.RefresherPageModule) },
	{ path: 'reorder', loadChildren: () => import('./pages/reorder/reorder.module').then(m => m.ReorderPageModule) },
	{ path: 'reorder/source', loadChildren: () => import('./pages/reorder/source/reorder-group.module').then(m => m.ReorderGroupPageModule) },
	{ path: 'ripple-effect/source', loadChildren: () => import('./pages/ripple-effect/source/ripple-effect.module').then(m => m.RippleEffectPageModule) },
	{ path: 'router-link', loadChildren: () => import('./pages/router-link/router-link.module').then(m => m.RouterLinkPageModule) },
	{ path: 'router-link/source', loadChildren: () => import('./pages/router-link/source/router-link.module').then(m => m.RouterLinkPageModule) },
	{ path: 'router-outlet/source', loadChildren: () => import('./pages/router-outlet/source/router-outlet.module').then(m => m.RouterOutletPageModule) },
	{ path: 'searchbar/preview-component', loadChildren: () => import('./pages/searchbar/preview-component/searchbar.module').then(m => m.SearchbarPageModule) },
	{ path: 'searchbar/preview', loadChildren: () => import('./pages/searchbar/preview/searchbars.module').then(m => m.SearchbarsPageModule) },
	{ path: 'searchbar', loadChildren: () => import('./pages/searchbar/searchbar.module').then(m => m.SearchbarPageModule) },
	{ path: 'searchbar/source', loadChildren: () => import('./pages/searchbar/source/searchbar.module').then(m => m.SearchbarPageModule) },
	{ path: 'segment/preview', loadChildren: () => import('./pages/segment/preview/segments.module').then(m => m.SegmentsPageModule) },
	{ path: 'segment', loadChildren: () => import('./pages/segment/segment.module').then(m => m.SegmentPageModule) },
	{ path: 'segment/source', loadChildren: () => import('./pages/segment/source/segment.module').then(m => m.SegmentPageModule) },
	{ path: 'select/preview-component', loadChildren: () => import('./pages/select/preview-component/select.module').then(m => m.SelectPageModule) },
	{ path: 'select/preview', loadChildren: () => import('./pages/select/preview/selects.module').then(m => m.SelectsPageModule) },
	{ path: 'select', loadChildren: () => import('./pages/select/select.module').then(m => m.SelectPageModule) },
	{ path: 'select/source', loadChildren: () => import('./pages/select/source/select.module').then(m => m.SelectPageModule) },
	{ path: 'site-bar/capacitor', loadChildren: () => import('./pages/site-bar/capacitor/site-bar.module').then(m => m.SiteBarPageModule) },
	{ path: 'site-header/capacitor', loadChildren: () => import('./pages/site-header/capacitor/site-header.module').then(m => m.SiteHeaderPageModule) },
	{ path: 'site-menu/capacitor', loadChildren: () => import('./pages/site-menu/capacitor/site-menu.module').then(m => m.SiteMenuPageModule) },
	{ path: 'skeleton-text', loadChildren: () => import('./pages/skeleton-text/skeleton-text.module').then(m => m.SkeletonTextPageModule) },
	{ path: 'skeleton-text/source', loadChildren: () => import('./pages/skeleton-text/source/skeleton-text.module').then(m => m.SkeletonTextPageModule) },
	{ path: 'slides/preview-component', loadChildren: () => import('./pages/slides/preview-component/slides.module').then(m => m.SlidesPageModule) },
	{ path: 'slides/preview', loadChildren: () => import('./pages/slides/preview/slides.module').then(m => m.SlidesPageModule) },
	{ path: 'slides', loadChildren: () => import('./pages/slides/slides.module').then(m => m.SlidesPageModule) },
	{ path: 'slides/source', loadChildren: () => import('./pages/slides/source/slides.module').then(m => m.SlidesPageModule) },
	{ path: 'spinner/preview-component', loadChildren: () => import('./pages/spinner/preview-component/spinner.module').then(m => m.SpinnerPageModule) },
	{ path: 'spinner/source', loadChildren: () => import('./pages/spinner/source/spinner.module').then(m => m.SpinnerPageModule) },
	{ path: 'spinner', loadChildren: () => import('./pages/spinner/spinner.module').then(m => m.SpinnerPageModule) },
	{ path: 'split-pane/source', loadChildren: () => import('./pages/split-pane/source/split-pane.module').then(m => m.SplitPanePageModule) },
	{ path: 'tab-bar/preview', loadChildren: () => import('./pages/tab-bar/preview/tabs.module').then(m => m.TabsPageModule) },
	{ path: 'tab-bar/source', loadChildren: () => import('./pages/tab-bar/source/tab-bar.module').then(m => m.TabBarPageModule) },
	{ path: 'text/source', loadChildren: () => import('./pages/text/source/text.module').then(m => m.TextPageModule) },
	{ path: 'text', loadChildren: () => import('./pages/text/text.module').then(m => m.TextPageModule) },
	{ path: 'textarea/source', loadChildren: () => import('./pages/textarea/source/textarea.module').then(m => m.TextareaPageModule) },
	{ path: 'thumbnail/source', loadChildren: () => import('./pages/thumbnail/source/thumbnail.module').then(m => m.ThumbnailPageModule) },
	{ path: 'thumbnail', loadChildren: () => import('./pages/thumbnail/thumbnail.module').then(m => m.ThumbnailPageModule) },
	{ path: 'title/source', loadChildren: () => import('./pages/title/source/title.module').then(m => m.TitlePageModule) },
	{ path: 'toast/preview-component', loadChildren: () => import('./pages/toast/preview-component/toast.module').then(m => m.ToastPageModule) },
	{ path: 'toast/preview', loadChildren: () => import('./pages/toast/preview/toast.module').then(m => m.ToastPageModule) },
	{ path: 'toast/source', loadChildren: () => import('./pages/toast/source/toast.module').then(m => m.ToastPageModule) },
	{ path: 'toast', loadChildren: () => import('./pages/toast/toast.module').then(m => m.ToastPageModule) },
	{ path: 'toggle/preview', loadChildren: () => import('./pages/toggle/preview/toggles.module').then(m => m.TogglesPageModule) },
	{ path: 'toggle/source', loadChildren: () => import('./pages/toggle/source/toggle.module').then(m => m.TogglePageModule) },
	{ path: 'toggle', loadChildren: () => import('./pages/toggle/toggle.module').then(m => m.TogglePageModule) },
	{ path: 'toolbar/preview/basic', loadChildren: () => import('./pages/toolbar/preview/basic/toolbar.module').then(m => m.ToolbarBasicPageModule) },
	{ path: 'toolbar/preview/buttons', loadChildren: () => import('./pages/toolbar/preview/buttons/toolbar.module').then(m => m.ToolbarButtonsPageModule) },
	{ path: 'toolbar/preview/colors', loadChildren: () => import('./pages/toolbar/preview/colors/toolbar.module').then(m => m.ToolbarColorsPageModule) },
	{ path: 'toolbar/preview/searchbar', loadChildren: () => import('./pages/toolbar/preview/searchbar/toolbar.module').then(m => m.ToolbarSearchbarPageModule) },
	{ path: 'toolbar/preview/segment', loadChildren: () => import('./pages/toolbar/preview/segment/toolbar.module').then(m => m.ToolbarSegmentPageModule) },
	{ path: 'toolbar/preview', loadChildren: () => import('./pages/toolbar/preview/toolbar.module').then(m => m.ToolbarPageModule) },
	{ path: 'toolbar/source', loadChildren: () => import('./pages/toolbar/source/toolbar.module').then(m => m.ToolbarPageModule) },
	{ path: 'toolbar', loadChildren: () => import('./pages/toolbar/toolbar.module').then(m => m.ToolbarPageModule) },
	{ path: 'virtual-scroll/preview-component', loadChildren: () => import('./pages/virtual-scroll/preview-component/virtual-scroll.module').then(m => m.VirtualScrollPageModule) },
	{ path: 'virtual-scroll/source', loadChildren: () => import('./pages/virtual-scroll/source/virtual-scroll.module').then(m => m.VirtualScrollPageModule) }

];

@NgModule({
	imports: [
		RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
	],
	exports: [RouterModule]
})
export class AppRoutingModule { }
